* Introduction
This file provides a set of configurations for the tools I used in my daily work and development.


** Terminal
*** Shell
**** ZSH
I use zsh as the default shell and use oh my zsh to manage it.
#+begin_src shell
# install and change default shell to zsh
sudo apt install -y zsh && chsh -s $(which zsh)
# install oh my zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
# install powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k
# install plugins
# zsh-autosuggestions
git clone --depth=1  https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
#zsh-syntax-highlighting
git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
#+end_src
After this create a symbolic link to the .zshrc file in the directory at ~~/.zshrc~ and do
#+begin_src shell
ln -s ~/dotconfig/zsh/zshrc ~/.zshrc
source ~/.zshrc
#+end_src
**** Bash
Sometimes have to use bash
**** Powershell
Sometimes you have to work on windows
**** Starship
This is used to provide same shell UI for all the different shells I come across.
*** Tmux
Version must be greater than 3.3, if package manager version is lower than than, can try to compile latest from source.
 #+begin_src shell
 ## compile latest from source
 sudo apt install -y libevent-dev bip
 ./configure && make -j$(proc)
 sudo make install

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
ln -s ~/dotconfig/tmux/.tmux.conf ~/.tmux.conf
tmux source-file ~/.tmux.conf
 #+end_src
 Use prefix+I to install tpm plugins
*** Terminal App
**** wezterm

** CLI tools
*** Zoxide
 #+begin_src powershell
 scoop install zoxide
 #+end_src

** TUI Apps
*** Neovim
*** Yazi
1.
2. create symbolic link for yazi config
https://github.com/ajeetdsouza/zoxide
 mklink /D "C:\Users\uie41442\AppData\Roaming\yazi\config" "C:\Users\uie41442\dotconfig\yazi"
 #+end_src



** Tiling Windows manager
*** aerospace
*** komorebi (Windows) 
1. use scoop to install komorebi and ahk
https://github.com/ajeetdsouza/zoxide
 scoop install komorebi autohotkey
 #+end_src
2. specify komori home directory in Powershell
 #+begin_src powershell
 $Env:KOMOREBI_CONFIG_HOME = Join-Path -Path $HOME -ChildPath '.config\komorebi'
 #+end_src
3. create symbolic link for config folder
4. autorun 

** Status bar
*** yasb (windows)
1. install yasb
 #+begin_src powershell
 winget install --id AmN.yasb
 #+end_src
2. create symbolic link for yazi config
 #+begin_src powershell
 mklink /D "C:\Users\uie41442\.config\yasb\" "C:\Users\uie41442\dotconfig\yazi"
 #+end_src
