# ~/.bashrc

source ~/.config/common/env
source ~/.config/common/aliases

# Load common functions
for f in ~/.config/common/functions/*; do
   [[ -f "$f" ]] && source "$f"
done
export SIYUAN_TOKEN=$(cat ~/.config/siyuan/token 2>/dev/null)
