source ~/.config/common/env
source ~/.config/common/aliases

# Fix brew completions for ARM Mac
if [[ "$(uname)" == "Darwin" && -d "/opt/homebrew/share/zsh/site-functions" ]]; then
  fpath=("${(@)fpath:#/usr/local/share/zsh/site-functions}")
  fpath=(/opt/homebrew/share/zsh/site-functions $fpath)
fi
for f in ~/.config/common/functions/*; do
    [ -f "$f" ] && source "$f"
done

source ~/.config/zsh/plugins.zsh
source ~/.config/zsh/vi.zsh
source ~/.config/zsh/fzf.zsh
autopair-init
source ~/.zim/modules/fzf-tab/fzf-tab.plugin.zsh
source ~/.config/zsh/prompt.zsh
# opencode

# API Keys
export GEMINI_API_KEY=$(get_netrc_pass "generativelanguage.googleapis.com")
export OPENAI_API_KEY=$(get_netrc_pass "api.openai.com")
export ANTHROPIC_API_KEY=$(get_netrc_pass "api.anthropic.com")
export OPENROUTER_API_KEY=$(get_netrc_pass "openrouter.ai")
export GLM_API_KEY=$(get_netrc_pass "z.ai")

# bun completions
[ -s "/home/uie41442/.bun/_bun" ] && source "/home/uie41442/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
