source ~/.config/common/env

# fnm
FNM_PATH="$HOME/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="$FNM_PATH:$PATH"
  eval "$(fnm env --shell zsh)"
fi

# Ensure WSL paths have precedence over Windows paths
if grep -qi "microsoft" /proc/version 2>/dev/null; then
  path=("${(@)path:#/mnt/c/*}")
  path+=(/mnt/c/Windows/system32 /mnt/c/Windows /mnt/c/Windows/System32/Wbem /mnt/c/Windows/System32/WindowsPowerShell/v1.0)
fi

source ~/.config/common/aliases

# Fix brew completions for ARM Mac
if [[ "$(uname)" == "Darwin" && -d "/opt/homebrew/share/zsh/site-functions" ]]; then
  fpath=("${(@)fpath:#/usr/local/share/zsh/site-functions}")
  fpath=(/opt/homebrew/share/zsh/site-functions $fpath)
fi
for f in ~/.config/common/functions/*; do
    [ -f "$f" ] && source "$f"
done

source ~/.config/zsh/plugins.zsh
source ~/.config/zsh/vi.zsh
source ~/.config/zsh/fzf.zsh
autopair-init
source ~/.zim/modules/fzf-tab/fzf-tab.plugin.zsh
source ~/.config/zsh/prompt.zsh
# opencode

# API Keys
export GEMINI_API_KEY=$(get_netrc_pass "generativelanguage.googleapis.com")
export OPENAI_API_KEY=$(get_netrc_pass "api.openai.com")
export ANTHROPIC_API_KEY=$(get_netrc_pass "api.anthropic.com")
export OPENROUTER_API_KEY=$(get_netrc_pass "openrouter.ai")
export GLM_API_KEY=$(get_netrc_pass "z.ai")

# bun completions
[ -s "/home/uie41442/.bun/_bun" ] && source "/home/uie41442/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


# Load MCP server credentials
[ -f "$HOME/.kiro/settings/mcp.env" ] && source "$HOME/.kiro/settings/mcp.env"
