source ~/.config/common/env
source ~/.config/common/aliases
for f in ~/.config/common/functions/*; do
    [ -f "$f" ] && source "$f"
done

source ~/.config/zsh/plugins.zsh
source ~/.config/zsh/vi.zsh
source ~/.config/zsh/fzf.zsh
autopair-init
source ~/.zim/modules/fzf-tab/fzf-tab.plugin.zsh
source ~/.config/zsh/prompt.zsh
# opencode

# API Keys
export GEMINI_API_KEY=$(get_netrc_pass "generativelanguage.googleapis.com")
export OPENAI_API_KEY=$(get_netrc_pass "api.openai.com")
export ANTHROPIC_API_KEY=$(get_netrc_pass "api.anthropic.com")
export OPENROUTER_API_KEY=$(get_netrc_pass "openrouter.ai")
