---
- name: Install command line tools
  hosts: localhost
  tasks:
    - name: Install command line tools on Mac or Linux via brew
      shell: >
        brew install 
        git
        unzip
        tmux 
        zsh 
        starship 
        ripgrep 
        fd 
        neovim 
        chezmoi 
        lazygit
        fzf
        tldr
        npm
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin:/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin"
      when: ansible_system in ["Darwin", "Linux"]

    - name: Install oh-my-zsh and zsh plugins
      shell: >
      sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)" \ 
      && git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting \
      && git clone --depth=1  https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
      when: ansible_system in ["Darwin", "Linux"]
 
    - name: Install command line tools on Windows
      shell: >
        scoop install 
        starship 
        ripgrep 
        fd 
        neovim
      when: ansible_system == "Windows"
