- name: Manage configuration with chezmoi
  hosts: localhost
  tasks:
    - name: Initialize chezmoi with a specified repository if not already initialized
      shell: |
        if [ ! -d "{{ ansible_env.HOME }}/.local/share/chezmoi" ]; then
          chezmoi init https://github.com/zhengfran/dotfiles.git
        fi
      args:
        executable: /bin/bash
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin:/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin"
      when: ansible_system in ["Darwin", "Linux"]

    - name: Apply chezmoi configuration
      shell: chezmoi apply
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin:/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin"
      when: ansible_system in ["Darwin", "Linux"]
