- name: Install emacs
  hosts: localhost
  tasks:
    - name: Install tools via brew to build emacs 29 from scratch
      shell: >
        brew install \
        gcc \
        libgccjit \
        glib \
        gtk+3 \
        jansson \
        automake \
        texinfo \
        tree-sitter \
        imagemagick \
        graphviz \
        plantuml
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin:/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin"
      when: ansible_system in ["Darwin", "Linux"]

    - name: Install tools via brew to build emacs 29 from scratch and run in wsl
      shell: >
        sudo apt install libwebkit2gtk-4.0-dev \
        libwebp-dev \
        adwaita-icon-theme-full
      when: ansible_os_family == "Debian"
      become: yes

    - name: Clone and build emacs
      shell: >
        git clone --depth 1 --branch emacs-29 git://git.sv.gnu.org/emacs.git ~/tools/emacs \
        && cd ~/tools/emacs \
        && ./autogen.sh \
        && ./configure --with-native-compilation --with-json --with-tree-sitter --with-xwidgets --with-pgtk --with-imagemagick --with-native-image-api \
        && make -j$(nproc)
      when: ansible_system in ["Darwin", "Linux"]

    - name : install emacs
      shell: sudo make install
      args:
        chdir: ~/tools/emacs/
      when: ansible_system in ["Darwin", "Linux"]

    - name : install doom emacs
      shell: >
        git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs \
        && ~/.config/emacs/bin/doom install --env
      when: ansible_system in ["Darwin", "Linux"]
