- name: Install Programming Language Related
  hosts: localhost
  tasks:
    - name: Install Rust
      shell: >
        brew install rust rust-analyzer
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin:/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin"
      when: ansible_system in ["Darwin", "Linux"]
    - name: Install Python3
      shell: >
        brew install python3
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin:/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin"
      when: ansible_system in ["Darwin", "Linux"]
