# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

plugins=(git z zsh-autosuggestions zsh-syntax-highlighting web-search)

source $ZSH/oh-my-zsh.sh

source ~/dotconfig/zsh/zsh_functions/aliases.zsh
source ~/dotconfig/zsh/zsh_functions/env.zsh
source ~/dotconfig/zsh/zsh_functions/general_func.zsh
source ~/dotconfig/zsh/zsh_functions/work_func.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

#use starship
eval "$(starship init zsh)"
