* Introduction
This file provides a set of configurations for the tools I used most often in my daily work and development.

* ZSH
I use zsh as the default shell and use oh my zsh to manage it, powerlevel10k is the zsh theme I currently use. Below is the command to install them
#+begin_src shell
  # install oh my zsh
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  # install powerlevel10k
  git clone https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k
  # install plugins
  # zsh-autosuggestions
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
  #zsh-syntax-highlighting
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
#+end_src
After this create a symbolic link to the .zshrc file in the directory at ~~/.zshrc~ and do
#+begin_src shell
source ~/.zshrc
#+end_src
By right the p10k configuration menu will popup, go through it should make it work.
* TMUX
 I use [[https://github.com/tmux-plugins/tpm][tpm]] ad the tmux plugin manager. 

* NeoVim
TODO
* Emacs
#+begin_src shell
# create symbolic links
ln -s ~/dotconfig/emacs/init.el ~/.emacs.d/init.el
ln -s ~/dotconfig/emacs/lisp ~/.emacs.d/lisp
#+end_src
Most emacs package I use will be automatically downloaded, but below packages needs mannual configuration:
** Emacs-rime
Link to [[https://github.com/DogLooksGood/emacs-rime][emacs-rime]].
For macos, need to download prebuilt librime releases and link it correct in the config file, for more details,refer to [[https://github.com/DogLooksGood/emacs-rime/blob/master/INSTALLATION.org][ 安装方法 ]] .
For macos, make sure these 2 variables are set correctly.
#+begin_src emacs-lisp
  ;;this works on my M1 Macbook Air
  (rime-emacs-module-header-root "/Applications/Emacs.app/Contents/Resources/include/")
  (rime-librime-root "~/.emacs.d/librime/dist")
#+end_src
** EAF
#+begin_src shell
git clone --depth=1 -b master https://github.com/emacs-eaf/emacs-application-framework.git ~/.emacs.d/site-lisp/emacs-application-framework/
#+end_src
